### ISSUE TITLE
Technical Issues

### ISSUE THREAD

**Issue by JosChavz** [thealicat13/blogium#3]
If this project is looking for improvement then read on:

Although I am a huge fan of GridBox and Flexbox, sometimes you have to know when to use it. 
It would be best if it was mobile-responsive, as most websites are so nowadays.
It's not good practice to make a website just with gridbox, it's similar as making it with a table, which developers used to do before.
.blog-card has an error: 
`grid-template-columns: 100%, auto, auto` → Remove the commas
[Read more here about CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/)

**Comment by thealicat13** [comment]
Thank you so much for pointing out the commas issue! Just fixed it. The mobile responsiveness should look much better now as well--realized I left off the viewport metatag!
